"""Generate refreshable clean routes for a static host; no API rewrites required."""

import json
import re
from html import escape as html_escape, unescape
from pathlib import Path
from urllib.parse import quote, urljoin, urlsplit
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
BASE_URL = "https://heliumtg.com"
MARKER = "<!-- Generated by scripts/build-clean-urls.py; edit the source template. -->"


def url_segment(value):
    # Match the site's encodeURIComponent URL builders, including its safe characters.
    return quote(str(value), safe="-_.!~*'()")


def page_metadata(template, manga, url, chapter=None):
    title = manga["title"]
    if chapter is not None:
        title += " – " + chapter["title"]
    description = (chapter or {}).get("description") or manga.get("description") or title
    description = unescape(re.sub(r"<[^>]*>", " ", description)).replace("\\n", " ")
    description = " ".join(description.split()) or title
    if len(description) > 300:
        description = description[:297].rsplit(" ", 1)[0] + "…"
    cover = urljoin(BASE_URL + "/", manga["cover"])
    parsed_cover = urlsplit(cover)
    if parsed_cover.scheme != "https" or not parsed_cover.hostname or parsed_cover.hostname in ("localhost", "127.0.0.1", "::1"):
        raise ValueError(f"Cover must be a public HTTPS URL: {cover!r}")

    # Replace generic tags rather than leaving duplicate values for crawlers.
    template = re.sub(r'<title\b[^>]*>.*?</title>', lambda _: f'<title id="page-title">{html_escape(title)} | HeliumTG</title>', template, flags=re.I | re.S)
    template = re.sub(r'<meta\b(?=[^>]*(?:name|property)\s*=\s*[\"\'](?:description|og:[^\"\']+|twitter:[^\"\']+)[\"\'])[^>]*>\s*', '', template, flags=re.I)
    template = re.sub(r'<link\b(?=[^>]*rel\s*=\s*[\"\']canonical[\"\'])[^>]*>\s*', '', template, flags=re.I)
    metadata = [f'<link rel="canonical" href="{html_escape(url, quote=True)}">']
    fields = [
        ("name", "description", description),
        ("property", "og:type", "article" if chapter is not None else "website"),
        ("property", "og:site_name", "HeliumTG"),
        ("property", "og:title", title),
        ("property", "og:description", description),
        ("property", "og:url", url),
        ("property", "og:image", cover),
        ("name", "twitter:card", "summary_large_image"),
        ("name", "twitter:title", title),
        ("name", "twitter:description", description),
        ("name", "twitter:image", cover),
    ]
    metadata.extend(f'<meta {attribute}="{key}" content="{html_escape(value, quote=True)}">' for attribute, key, value in fields)
    return template.replace('</head>', '\n'.join(metadata) + '\n  </head>', 1)


def build():
    data = json.loads((ROOT / "assets/data/data.json").read_text(encoding="utf-8"))
    routes = {
        "login": "login.html",
        "follow": "follow.html",
        "history": "history.html",
        "user": "user.html",
        "admin/manga": "admin/manga.html",
        "admin/chapter": "admin/chapter.html",
    }
    urls = ["/", "/follow/", "/history/", "/user/"]
    metadata = {}
    for slug, manga in data.items():
        # Catalogue keys must be safe directory components as well as URL segments.
        if not slug or slug in (".", "..") or "/" in slug or "\\" in slug:
            raise ValueError(f"Unsafe manga slug: {slug!r}")
        route = f"manga/{slug}"
        routes[route] = "manga.html"
        manga_url = f"/manga/{url_segment(slug)}/"
        urls.append(manga_url)
        metadata[route] = (manga, BASE_URL + manga_url, None)
        for chapter in manga.get("chapters", []):
            chapter_id = chapter.get("id")
            if chapter_id is None:
                continue
            segment = str(chapter_id)
            if not segment or segment in (".", "..") or "/" in segment or "\\" in segment:
                raise ValueError(f"Unsafe chapter ID: {segment!r}")
            chapter_route = f"{route}/chapter/{segment}"
            routes[chapter_route] = "chapter.html"
            chapter_url = f"{manga_url}chapter/{url_segment(segment)}/"
            urls.append(chapter_url)
            metadata[chapter_route] = (manga, BASE_URL + chapter_url, chapter)

    expected = {ROOT / route / "index.html" for route in routes}
    # Remove only files created by this generator when catalogue routes disappear.
    for folder in ("manga", "login", "follow", "history", "user", "admin/manga", "admin/chapter"):
        for old in (ROOT / folder).rglob("index.html"):
            if old not in expected and old.read_text(encoding="utf-8").startswith(MARKER):
                old.unlink()

    templates = {source: (ROOT / source).read_text(encoding="utf-8") for source in set(routes.values())}
    for route, source in routes.items():
        output = ROOT / route / "index.html"
        output.parent.mkdir(parents=True, exist_ok=True)
        html = templates[source]
        if route in metadata:
            html = page_metadata(html, *metadata[route])
        output.write_text(MARKER + "\n" + html, encoding="utf-8")

    xml = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for url in dict.fromkeys(urls):
        xml.extend(["  <url>", f"    <loc>{escape(BASE_URL + url)}</loc>", "  </url>"])
    xml.append("</urlset>")
    (ROOT / "sitemap.xml").write_text("\n".join(xml), encoding="utf-8")
    print(f"Generated {len(routes)} clean route files and {len(set(urls))} sitemap URLs.")


if __name__ == "__main__":
    build()
